schemes = [

    # ════════════════════════════
    # 1. AGRICULTURE (10 schemes)
    # ════════════════════════════
    {"id":1,"name":"PM Kisan Samman Nidhi","category":"Agriculture","description":"Financial support of ₹6,000/year to small and marginal farmers.","benefit":"₹6,000/year in 3 installments","eligibility":{"occupation":["farmer"],"max_income":150000},"apply_link":"https://pmkisan.gov.in","icon":"🌾"},
    {"id":2,"name":"Kisan Credit Card","category":"Agriculture","description":"Short-term credit for farmers to meet agricultural and allied needs.","benefit":"Credit up to ₹3 lakh at 4% interest","eligibility":{"occupation":["farmer"]},"apply_link":"https://www.nabard.org","icon":"💳"},
    {"id":3,"name":"PM Fasal Bima Yojana","category":"Agriculture","description":"Crop insurance scheme providing financial support during crop loss.","benefit":"Crop loss insurance at low premium","eligibility":{"occupation":["farmer"]},"apply_link":"https://pmfby.gov.in","icon":"🌱"},
    {"id":4,"name":"Pradhan Mantri Krishi Sinchai Yojana","category":"Agriculture","description":"Ensures access to water for every farm to improve irrigation.","benefit":"Irrigation infrastructure support","eligibility":{"occupation":["farmer"]},"apply_link":"https://pmksy.gov.in","icon":"💧"},
    {"id":5,"name":"Soil Health Card Scheme","category":"Agriculture","description":"Provides soil health cards to farmers with crop-wise recommendations.","benefit":"Free soil testing and recommendations","eligibility":{"occupation":["farmer"]},"apply_link":"https://soilhealth.dac.gov.in","icon":"🧪"},
    {"id":6,"name":"Paramparagat Krishi Vikas Yojana","category":"Agriculture","description":"Promotes organic farming through cluster-based approach.","benefit":"₹50,000/hectare for organic farming","eligibility":{"occupation":["farmer"]},"apply_link":"https://pgsindia-ncof.gov.in","icon":"🌿"},
    {"id":7,"name":"PM Kisan Maan Dhan Yojana","category":"Agriculture","description":"Pension scheme for small and marginal farmers after age 60.","benefit":"₹3,000/month pension after 60","eligibility":{"occupation":["farmer"],"min_age":18,"max_age":40},"apply_link":"https://pmkmy.gov.in","icon":"👨‍🌾"},
    {"id":8,"name":"National Mission for Sustainable Agriculture","category":"Agriculture","description":"Promotes climate resilient agriculture practices.","benefit":"Financial aid for sustainable farming","eligibility":{"occupation":["farmer"]},"apply_link":"https://nmsa.dac.gov.in","icon":"☘️"},
    {"id":9,"name":"Agricultural Infrastructure Fund","category":"Agriculture","description":"Financing facility for agriculture infrastructure projects.","benefit":"Loan up to ₹2 crore at subsidized rate","eligibility":{"occupation":["farmer","self-employed"]},"apply_link":"https://agriinfra.dac.gov.in","icon":"🏗️"},
    {"id":10,"name":"PM Annadata Aay SanraksHan Abhiyan","category":"Agriculture","description":"Ensures farmers get minimum support price for their produce.","benefit":"MSP guarantee for crops","eligibility":{"occupation":["farmer"]},"apply_link":"https://agriculture.gov.in","icon":"🌽"},

    # ════════════════════════════
    # 2. EDUCATION (10 schemes)
    # ════════════════════════════
    {"id":11,"name":"Post Matric Scholarship for SC Students","category":"Education","description":"Scholarship for SC students studying post-matriculation courses.","benefit":"Full tuition + maintenance allowance","eligibility":{"category":["SC"],"max_age":30,"max_income":250000},"apply_link":"https://scholarships.gov.in","icon":"📚"},
    {"id":12,"name":"Post Matric Scholarship for ST Students","category":"Education","description":"Scholarship for ST students studying post-matriculation courses.","benefit":"Full tuition + maintenance allowance","eligibility":{"category":["ST"],"max_age":30,"max_income":250000},"apply_link":"https://scholarships.gov.in","icon":"📖"},
    {"id":13,"name":"National Scholarship Portal OBC","category":"Education","description":"Pre and post matric scholarships for OBC students.","benefit":"₹1,000–₹10,000 per year","eligibility":{"category":["OBC"],"max_income":100000},"apply_link":"https://scholarships.gov.in","icon":"🎓"},
    {"id":14,"name":"PM Vidya Lakshmi Education Loan","category":"Education","description":"Education loan for higher studies with interest subsidy.","benefit":"Interest subsidy on education loans","eligibility":{"max_income":450000},"apply_link":"https://www.vidyalakshmi.co.in","icon":"🏫"},
    {"id":15,"name":"National Means Cum Merit Scholarship","category":"Education","description":"Scholarship to meritorious students from economically weaker sections.","benefit":"₹12,000/year scholarship","eligibility":{"max_income":150000,"max_age":18},"apply_link":"https://scholarships.gov.in","icon":"🥇"},
    {"id":16,"name":"Pradhan Mantri Uchchatar Shiksha Abhiyan","category":"Education","description":"Improves access and quality of higher education institutions.","benefit":"Higher education quality grants","eligibility":{"occupation":["student"]},"apply_link":"https://rusa.nic.in","icon":"🎯"},
    {"id":17,"name":"Ishan Uday Scholarship","category":"Education","description":"Special scholarship for students from North East region.","benefit":"₹5,400–₹7,800/month scholarship","eligibility":{"max_income":450000,"occupation":["student"]},"apply_link":"https://scholarships.gov.in","icon":"⭐"},
    {"id":18,"name":"Central Sector Scholarship Scheme","category":"Education","description":"Scholarship for college and university students from low income families.","benefit":"₹10,000–₹20,000/year","eligibility":{"max_income":450000,"occupation":["student"]},"apply_link":"https://scholarships.gov.in","icon":"📝"},
    {"id":19,"name":"Pragati Scholarship for Girl Students","category":"Education","description":"Scholarship for girl students pursuing technical education.","benefit":"₹30,000/year + tuition fee","eligibility":{"gender":["female"],"occupation":["student"],"max_income":800000},"apply_link":"https://www.aicte-india.org","icon":"👩‍🎓"},
    {"id":20,"name":"Saksham Scholarship for Disabled Students","category":"Education","description":"Scholarship for differently abled students in technical courses.","benefit":"₹30,000/year + tuition fee","eligibility":{"occupation":["student"]},"apply_link":"https://www.aicte-india.org","icon":"♿"},

    # ════════════════════════════
    # 3. HEALTH (10 schemes)
    # ════════════════════════════
    {"id":21,"name":"Ayushman Bharat PM-JAY","category":"Health","description":"Health insurance cover of ₹5 lakh per family per year.","benefit":"₹5 lakh health cover/family/year","eligibility":{"max_income":200000},"apply_link":"https://pmjay.gov.in","icon":"🏥"},
    {"id":22,"name":"PM Jeevan Jyoti Bima Yojana","category":"Health","description":"Life insurance cover of ₹2 lakh at just ₹436/year.","benefit":"₹2 lakh life cover at ₹436/year","eligibility":{"min_age":18,"max_age":50},"apply_link":"https://jansuraksha.gov.in","icon":"🛡️"},
    {"id":23,"name":"PM Suraksha Bima Yojana","category":"Health","description":"Accident insurance cover of ₹2 lakh at just ₹20/year.","benefit":"₹2 lakh accident cover at ₹20/year","eligibility":{"min_age":18,"max_age":70},"apply_link":"https://jansuraksha.gov.in","icon":"🚑"},
    {"id":24,"name":"Janani Suraksha Yojana","category":"Health","description":"Safe motherhood scheme promoting institutional delivery.","benefit":"₹1,400 cash for delivery in institution","eligibility":{"gender":["female"],"max_income":100000},"apply_link":"https://nhm.gov.in","icon":"🤱"},
    {"id":25,"name":"Pradhan Mantri Matru Vandana Yojana","category":"Health","description":"Maternity benefit program providing cash support to pregnant women.","benefit":"₹5,000 direct cash benefit","eligibility":{"gender":["female"]},"apply_link":"https://pmmvy.nic.in","icon":"👶"},
    {"id":26,"name":"National Health Mission","category":"Health","description":"Universal health coverage focusing on rural and remote areas.","benefit":"Free health services at public facilities","eligibility":{"max_income":200000},"apply_link":"https://nhm.gov.in","icon":"💊"},
    {"id":27,"name":"Ayushman Bharat Health Wellness Centres","category":"Health","description":"Comprehensive primary health care close to communities.","benefit":"Free primary healthcare services","eligibility":{},"apply_link":"https://ab-hwc.nhp.gov.in","icon":"🏨"},
    {"id":28,"name":"Rashtriya Arogya Nidhi","category":"Health","description":"Financial assistance for BPL patients with life threatening diseases.","benefit":"Up to ₹15 lakh for critical illness","eligibility":{"max_income":100000},"apply_link":"https://mohfw.gov.in","icon":"❤️"},
    {"id":29,"name":"PM TB Mukt Bharat Abhiyan","category":"Health","description":"Nutritional support for TB patients undergoing treatment.","benefit":"₹500/month nutrition support","eligibility":{},"apply_link":"https://nikshay.in","icon":"🫁"},
    {"id":30,"name":"National Mental Health Programme","category":"Health","description":"Free mental health services and treatment across India.","benefit":"Free mental health treatment","eligibility":{},"apply_link":"https://nhm.gov.in","icon":"🧠"},

    # ════════════════════════════
    # 4. WOMEN & CHILD (10 schemes)
    # ════════════════════════════
    {"id":31,"name":"Sukanya Samriddhi Yojana","category":"Women & Child","description":"Savings scheme for girl child with high interest and tax benefits.","benefit":"8.2% interest + tax exemption","eligibility":{"gender":["female"],"max_age":10},"apply_link":"https://www.indiapost.gov.in","icon":"👧"},
    {"id":32,"name":"Beti Bachao Beti Padhao","category":"Women & Child","description":"Scheme to promote girl child education and prevent gender bias.","benefit":"Education support + awareness programs","eligibility":{"gender":["female"],"max_age":18},"apply_link":"https://wcd.nic.in","icon":"🎓"},
    {"id":33,"name":"PM Ujjwala Yojana","category":"Women & Child","description":"Free LPG connections to women from BPL households.","benefit":"Free LPG connection + first refill","eligibility":{"gender":["female"],"max_income":100000},"apply_link":"https://pmuy.gov.in","icon":"🔥"},
    {"id":34,"name":"Mahila Shakti Kendra","category":"Women & Child","description":"Empowers rural women through community participation.","benefit":"Skill training + awareness programs","eligibility":{"gender":["female"]},"apply_link":"https://wcd.nic.in","icon":"💪"},
    {"id":35,"name":"One Stop Centre Scheme","category":"Women & Child","description":"Integrated support for women affected by violence.","benefit":"Free legal + medical + shelter support","eligibility":{"gender":["female"]},"apply_link":"https://wcd.nic.in","icon":"🏠"},
    {"id":36,"name":"Poshan Abhiyaan","category":"Women & Child","description":"Nutrition mission to reduce malnutrition among children and women.","benefit":"Nutritional support + health services","eligibility":{"gender":["female"],"max_age":6},"apply_link":"https://poshanabhiyaan.gov.in","icon":"🥗"},
    {"id":37,"name":"Integrated Child Development Services","category":"Women & Child","description":"Nutrition, health and education for children under 6.","benefit":"Free nutrition + healthcare for children","eligibility":{"max_age":6},"apply_link":"https://icds-wcd.nic.in","icon":"👼"},
    {"id":38,"name":"Widow Remarriage Scheme","category":"Women & Child","description":"Financial incentive for widow remarriage to prevent isolation.","benefit":"₹2 lakh incentive for remarriage","eligibility":{"gender":["female"]},"apply_link":"https://wcd.nic.in","icon":"💐"},
    {"id":39,"name":"Working Women Hostel Scheme","category":"Women & Child","description":"Safe hostel accommodation for working women.","benefit":"Subsidized safe accommodation","eligibility":{"gender":["female"],"occupation":["salaried","self-employed"]},"apply_link":"https://wcd.nic.in","icon":"🏢"},
    {"id":40,"name":"PM Balika Anudan Yojana","category":"Women & Child","description":"Financial assistance for marriage of BPL family daughters.","benefit":"₹50,000 for girl's marriage","eligibility":{"gender":["female"],"max_income":100000},"apply_link":"https://wcd.nic.in","icon":"💍"},

    # ════════════════════════════
    # 5. EMPLOYMENT (10 schemes)
    # ════════════════════════════
    {"id":41,"name":"PM Mudra Yojana","category":"Employment","description":"Loans up to ₹10 lakh for non-farm micro enterprises.","benefit":"Collateral-free loan ₹50K–₹10 lakh","eligibility":{"occupation":["self-employed","unemployed"]},"apply_link":"https://mudra.org.in","icon":"💼"},
    {"id":42,"name":"Atal Pension Yojana","category":"Employment","description":"Guaranteed pension for unorganized sector workers after 60.","benefit":"₹1,000–₹5,000/month pension","eligibility":{"min_age":18,"max_age":40,"occupation":["laborer","farmer","self-employed","unemployed"]},"apply_link":"https://npscra.nsdl.co.in","icon":"🏦"},
    {"id":43,"name":"Stand Up India","category":"Employment","description":"Bank loans for SC/ST and women entrepreneurs.","benefit":"Loan ₹10 lakh–₹1 crore for business","eligibility":{"category":["SC","ST"],"occupation":["self-employed","unemployed"]},"apply_link":"https://www.standupmitra.in","icon":"🚀"},
    {"id":44,"name":"PM Employment Generation Programme","category":"Employment","description":"Credit-linked subsidy for setting up micro enterprises.","benefit":"Up to 35% subsidy on project cost","eligibility":{"occupation":["unemployed","self-employed"],"max_age":45},"apply_link":"https://kviconline.gov.in","icon":"🏭"},
    {"id":45,"name":"MGNREGA","category":"Employment","description":"Guarantees 100 days of wage employment per year to rural households.","benefit":"100 days guaranteed employment/year","eligibility":{"occupation":["laborer","unemployed","farmer"]},"apply_link":"https://nrega.nic.in","icon":"⛏️"},
    {"id":46,"name":"PM SVANidhi Scheme","category":"Employment","description":"Micro credit for street vendors to restart livelihoods.","benefit":"Loan ₹10,000–₹50,000 for vendors","eligibility":{"occupation":["self-employed","unemployed"]},"apply_link":"https://pmsvanidhi.mohua.gov.in","icon":"🛒"},
    {"id":47,"name":"Startup India","category":"Employment","description":"Support for startups with tax exemption and funding access.","benefit":"Tax exemption + funding + mentorship","eligibility":{"occupation":["self-employed"]},"apply_link":"https://www.startupindia.gov.in","icon":"💡"},
    {"id":48,"name":"National Apprenticeship Promotion Scheme","category":"Employment","description":"Promotes apprenticeship training in industries.","benefit":"₹1,500/month stipend support","eligibility":{"occupation":["unemployed","student"],"max_age":30},"apply_link":"https://apprenticeship.gov.in","icon":"🔧"},
    {"id":49,"name":"PM Kaushal Vikas Yojana","category":"Employment","description":"Free skill training for youth to improve employability.","benefit":"Free skill training + ₹8,000 reward","eligibility":{"occupation":["unemployed","student"],"max_age":35},"apply_link":"https://pmkvyofficial.org","icon":"🛠️"},
    {"id":50,"name":"Deen Dayal Upadhyaya Grameen Kaushalya","category":"Employment","description":"Placement-linked skill training for rural youth.","benefit":"Free training + guaranteed placement","eligibility":{"occupation":["unemployed"],"min_age":15,"max_age":35},"apply_link":"https://ddugky.gov.in","icon":"🌍"},

    # ════════════════════════════
    # 6. HOUSING (10 schemes)
    # ════════════════════════════
    {"id":51,"name":"Pradhan Mantri Awas Yojana Urban","category":"Housing","description":"Affordable housing for urban poor with interest subsidy.","benefit":"Interest subsidy up to ₹2.67 lakh","eligibility":{"max_income":1800000},"apply_link":"https://pmaymis.gov.in","icon":"🏠"},
    {"id":52,"name":"Pradhan Mantri Awas Yojana Gramin","category":"Housing","description":"Housing assistance for rural BPL families.","benefit":"₹1.2–1.3 lakh for house construction","eligibility":{"max_income":100000,"occupation":["farmer","laborer","unemployed"]},"apply_link":"https://pmayg.nic.in","icon":"🏡"},
    {"id":53,"name":"Rajiv Awas Yojana","category":"Housing","description":"Slum-free India mission providing housing to slum dwellers.","benefit":"Housing support for slum residents","eligibility":{"max_income":100000},"apply_link":"https://mhupa.gov.in","icon":"🏘️"},
    {"id":54,"name":"Credit Linked Subsidy Scheme","category":"Housing","description":"Interest subsidy on home loans for EWS and LIG categories.","benefit":"Interest subsidy ₹2.35–₹2.67 lakh","eligibility":{"max_income":1800000},"apply_link":"https://pmaymis.gov.in","icon":"🔑"},
    {"id":55,"name":"National Urban Livelihood Mission Housing","category":"Housing","description":"Shelter for urban homeless with basic amenities.","benefit":"Free shelter + basic amenities","eligibility":{"max_income":100000,"occupation":["unemployed","laborer"]},"apply_link":"https://nulm.gov.in","icon":"🏗️"},
    {"id":56,"name":"Indira Awas Yojana","category":"Housing","description":"Provides housing assistance to SC/ST and freed bonded laborers.","benefit":"₹70,000–₹75,000 for house construction","eligibility":{"category":["SC","ST"],"max_income":100000},"apply_link":"https://rural.nic.in","icon":"🏚️"},
    {"id":57,"name":"PM Awas Yojana for Disabled","category":"Housing","description":"Special housing assistance for differently abled persons.","benefit":"₹1.5 lakh housing grant","eligibility":{"max_income":100000},"apply_link":"https://pmaymis.gov.in","icon":"♿"},
    {"id":58,"name":"Housing for All Mission","category":"Housing","description":"Ensures every family has a pucca house by 2024.","benefit":"Financial assistance for pucca house","eligibility":{"max_income":300000},"apply_link":"https://mohua.gov.in","icon":"🏛️"},
    {"id":59,"name":"Affordable Rental Housing Complexes","category":"Housing","description":"Affordable rental housing for urban migrants and poor.","benefit":"Subsidized rental housing","eligibility":{"occupation":["laborer","salaried"],"max_income":300000},"apply_link":"https://mohua.gov.in","icon":"🏢"},
    {"id":60,"name":"Rural Housing Interest Subsidy Scheme","category":"Housing","description":"Interest subsidy for rural people taking home loans.","benefit":"6% interest subsidy on home loans","eligibility":{"max_income":200000,"occupation":["farmer","laborer"]},"apply_link":"https://nhb.org.in","icon":"🌄"},

    # ════════════════════════════
    # 7. SENIOR CITIZENS (10 schemes)
    # ════════════════════════════
    {"id":61,"name":"National Old Age Pension Scheme","category":"Senior Citizens","description":"Monthly pension for senior citizens above 60 years.","benefit":"₹200–₹500/month pension","eligibility":{"min_age":60,"max_income":100000},"apply_link":"https://nsap.nic.in","icon":"👴"},
    {"id":62,"name":"Indira Gandhi National Old Age Pension","category":"Senior Citizens","description":"Pension for BPL senior citizens above 60.","benefit":"₹200–₹500/month pension","eligibility":{"min_age":60,"max_income":100000},"apply_link":"https://nsap.nic.in","icon":"👵"},
    {"id":63,"name":"Varishtha Pension Bima Yojana","category":"Senior Citizens","description":"Pension scheme for senior citizens with guaranteed return.","benefit":"Guaranteed 7.4% return on investment","eligibility":{"min_age":60},"apply_link":"https://licindia.in","icon":"💰"},
    {"id":64,"name":"Senior Citizen Savings Scheme","category":"Senior Citizens","description":"High interest savings scheme for senior citizens.","benefit":"8.2% interest rate per annum","eligibility":{"min_age":60},"apply_link":"https://www.indiapost.gov.in","icon":"🏦"},
    {"id":65,"name":"Pradhan Mantri Vaya Vandana Yojana","category":"Senior Citizens","description":"Pension scheme offering assured return for senior citizens.","benefit":"7.4% guaranteed return + pension","eligibility":{"min_age":60},"apply_link":"https://licindia.in","icon":"📊"},
    {"id":66,"name":"Rashtriya Vayoshri Yojana","category":"Senior Citizens","description":"Free assistive devices for senior citizens from BPL households.","benefit":"Free wheelchair, hearing aid, glasses etc.","eligibility":{"min_age":60,"max_income":100000},"apply_link":"https://rvy.gov.in","icon":"🦽"},
    {"id":67,"name":"National Programme for Health Care of Elderly","category":"Senior Citizens","description":"Dedicated healthcare services for elderly citizens.","benefit":"Free health checkup + treatment","eligibility":{"min_age":60},"apply_link":"https://nhm.gov.in","icon":"🏥"},
    {"id":68,"name":"Elder Line 14567","category":"Senior Citizens","description":"National helpline for senior citizens providing assistance.","benefit":"Free helpline + emergency support","eligibility":{"min_age":60},"apply_link":"https://elderline.gov.in","icon":"📞"},
    {"id":69,"name":"Annapurna Scheme","category":"Senior Citizens","description":"10 kg free food grains per month to destitute senior citizens.","benefit":"10 kg free food grains/month","eligibility":{"min_age":65,"max_income":100000},"apply_link":"https://dfpd.gov.in","icon":"🍚"},
    {"id":70,"name":"Income Tax Exemption for Senior Citizens","category":"Senior Citizens","description":"Higher income tax exemption limit for senior citizens.","benefit":"₹3–5 lakh tax exemption","eligibility":{"min_age":60},"apply_link":"https://incometaxindia.gov.in","icon":"📋"},

    # ════════════════════════════
    # 8. SC/ST SPECIFIC (10 schemes)
    # ════════════════════════════
    {"id":71,"name":"National SC Finance Corporation Loan","category":"SC/ST","description":"Concessional loans for SC persons to start businesses.","benefit":"Loan at 6% interest for SC people","eligibility":{"category":["SC"],"max_income":300000},"apply_link":"https://nsfdc.nic.in","icon":"💳"},
    {"id":72,"name":"National ST Finance Corporation Loan","category":"SC/ST","description":"Concessional loans for ST persons for income generation.","benefit":"Loan at 6% interest for ST people","eligibility":{"category":["ST"],"max_income":300000},"apply_link":"https://nstfdc.nic.in","icon":"💰"},
    {"id":73,"name":"Dr. Ambedkar Post Matric Scholarship","category":"SC/ST","description":"Scholarship for OBC and EBC students for post-matric education.","benefit":"Full fees + maintenance allowance","eligibility":{"category":["OBC","SC","ST"],"max_income":300000},"apply_link":"https://scholarships.gov.in","icon":"🎓"},
    {"id":74,"name":"Pre Matric Scholarship for SC Students","category":"SC/ST","description":"Scholarship for SC students studying in class 9 and 10.","benefit":"₹1,000–₹3,500/month scholarship","eligibility":{"category":["SC"],"max_age":18,"max_income":250000},"apply_link":"https://scholarships.gov.in","icon":"📚"},
    {"id":75,"name":"Pre Matric Scholarship for ST Students","category":"SC/ST","description":"Scholarship for ST students studying in class 9 and 10.","benefit":"₹1,000–₹3,500/month scholarship","eligibility":{"category":["ST"],"max_age":18,"max_income":250000},"apply_link":"https://scholarships.gov.in","icon":"📖"},
    {"id":76,"name":"Venture Capital Fund for SC/ST","category":"SC/ST","description":"Risk capital for SC/ST entrepreneurs starting new businesses.","benefit":"Equity funding up to ₹15 lakh","eligibility":{"category":["SC","ST"],"occupation":["self-employed","unemployed"]},"apply_link":"https://nsfdc.nic.in","icon":"🚀"},
    {"id":77,"name":"Special Central Assistance to SC Sub Plan","category":"SC/ST","description":"Family-based income generation schemes for SC families.","benefit":"Income generating assets + training","eligibility":{"category":["SC"],"max_income":100000},"apply_link":"https://socialjustice.gov.in","icon":"🌟"},
    {"id":78,"name":"Babu Jagjivan Ram Chhatrawas Yojana","category":"SC/ST","description":"Hostel facilities for SC/ST students for education.","benefit":"Free hostel for SC/ST students","eligibility":{"category":["SC","ST"],"occupation":["student"]},"apply_link":"https://socialjustice.gov.in","icon":"🏫"},
    {"id":79,"name":"Free Coaching Scheme for SC/ST","category":"SC/ST","description":"Free coaching for competitive exams for SC/ST students.","benefit":"Free coaching for IIT/UPSC/banking exams","eligibility":{"category":["SC","ST"],"max_income":800000},"apply_link":"https://socialjustice.gov.in","icon":"✏️"},
    {"id":80,"name":"Nai Roshni Leadership for Minority Women","category":"SC/ST","description":"Leadership development program for minority women.","benefit":"Free leadership + skill training","eligibility":{"gender":["female"],"category":["SC","ST","OBC"]},"apply_link":"https://minorityaffairs.gov.in","icon":"💫"},

    # ════════════════════════════
    # 9. DISABILITY (10 schemes)
    # ════════════════════════════
    {"id":81,"name":"Divyangjan Scholarship Scheme","category":"Disability","description":"Scholarships for differently abled students at various levels.","benefit":"₹500–₹2,000/month scholarship","eligibility":{"occupation":["student"]},"apply_link":"https://scholarships.gov.in","icon":"♿"},
    {"id":82,"name":"Assistance to Disabled Persons for Devices","category":"Disability","description":"Free aids and assistive devices for persons with disabilities.","benefit":"Free assistive devices worth ₹10,000+","eligibility":{"max_income":200000},"apply_link":"https://alimco.in","icon":"🦽"},
    {"id":83,"name":"Deen Dayal Disabled Rehabilitation Scheme","category":"Disability","description":"Financial assistance for NGOs running rehabilitation programs.","benefit":"Free rehabilitation services","eligibility":{},"apply_link":"https://disabilityaffairs.gov.in","icon":"🤝"},
    {"id":84,"name":"National Handicapped Finance Corporation Loan","category":"Disability","description":"Concessional loans for differently abled persons to start business.","benefit":"Loan at 5% interest for disabled persons","eligibility":{"max_income":300000},"apply_link":"https://nhfdc.nic.in","icon":"💳"},
    {"id":85,"name":"Unique Disability ID Card","category":"Disability","description":"Official ID card for persons with disabilities to access benefits.","benefit":"Access to all disability schemes + discounts","eligibility":{},"apply_link":"https://swavlambancard.gov.in","icon":"🪪"},
    {"id":86,"name":"Indira Gandhi National Disability Pension","category":"Disability","description":"Monthly pension for severely disabled BPL persons.","benefit":"₹300/month disability pension","eligibility":{"max_income":100000},"apply_link":"https://nsap.nic.in","icon":"👐"},
    {"id":87,"name":"Free Travel for Disabled in Railways","category":"Disability","description":"75% concession on railway fares for persons with disabilities.","benefit":"75% discount on train tickets","eligibility":{},"apply_link":"https://indianrailways.gov.in","icon":"🚂"},
    {"id":88,"name":"National Trust Scholarship","category":"Disability","description":"Scholarships for students with autism, cerebral palsy and disabilities.","benefit":"₹700–₹4,000/month scholarship","eligibility":{"occupation":["student"]},"apply_link":"https://thenationaltrust.gov.in","icon":"🌈"},
    {"id":89,"name":"PM Daksh Yojana for Disabled","category":"Disability","description":"Skill development training for differently abled persons.","benefit":"Free skill training + stipend","eligibility":{"occupation":["unemployed"]},"apply_link":"https://disabilityaffairs.gov.in","icon":"🛠️"},
    {"id":90,"name":"Accessible India Campaign","category":"Disability","description":"Making public spaces accessible for persons with disabilities.","benefit":"Accessible infrastructure + ramps","eligibility":{},"apply_link":"https://disabilityaffairs.gov.in","icon":"🏛️"},

    # ════════════════════════════
    # 10. YOUTH & SPORTS (10 schemes)
    # ════════════════════════════
    {"id":91,"name":"Khelo India Programme","category":"Youth & Sports","description":"Grassroots sports development and talent identification.","benefit":"₹5 lakh/year for identified athletes","eligibility":{"max_age":21},"apply_link":"https://kheloindia.gov.in","icon":"🏃"},
    {"id":92,"name":"National Sports Development Fund","category":"Youth & Sports","description":"Financial support for elite athletes for training and competition.","benefit":"Training + competition funding","eligibility":{"occupation":["student"]},"apply_link":"https://yas.nic.in","icon":"🏅"},
    {"id":93,"name":"PM Yuva Yojana","category":"Youth & Sports","description":"Entrepreneurship education for youth through higher education.","benefit":"Entrepreneurship training + mentorship","eligibility":{"occupation":["student"],"max_age":30},"apply_link":"https://msde.gov.in","icon":"💡"},
    {"id":94,"name":"Nehru Yuva Kendra Sangathan","category":"Youth & Sports","description":"Youth development programs at block level across India.","benefit":"Leadership + skill development programs","eligibility":{"min_age":18,"max_age":29},"apply_link":"https://nyks.nic.in","icon":"🌟"},
    {"id":95,"name":"National Youth Corps","category":"Youth & Sports","description":"Voluntary service opportunity for youth in community development.","benefit":"₹5,000/month stipend","eligibility":{"min_age":18,"max_age":25},"apply_link":"https://nyks.nic.in","icon":"🤝"},
    {"id":96,"name":"Rajiv Gandhi Khel Abhiyan","category":"Youth & Sports","description":"Rural sports infrastructure development and talent promotion.","benefit":"Sports infrastructure + coaching","eligibility":{"max_age":25},"apply_link":"https://yas.nic.in","icon":"⚽"},
    {"id":97,"name":"Target Olympic Podium Scheme","category":"Youth & Sports","description":"Support for top athletes preparing for Olympics.","benefit":"World-class training + financial support","eligibility":{"occupation":["student"]},"apply_link":"https://yas.nic.in","icon":"🥇"},
    {"id":98,"name":"National Service Scheme","category":"Youth & Sports","description":"Personality development through community service for students.","benefit":"Certificate + scholarship opportunities","eligibility":{"occupation":["student"],"min_age":15,"max_age":25},"apply_link":"https://nss.gov.in","icon":"🎖️"},
    {"id":99,"name":"Sports Authority of India Coaching","category":"Youth & Sports","description":"Free coaching at SAI centres for talented young athletes.","benefit":"Free coaching + accommodation + meals","eligibility":{"max_age":25},"apply_link":"https://sai.gov.in","icon":"🏋️"},
    {"id":100,"name":"Atal Innovation Mission","category":"Youth & Sports","description":"Fosters innovation and entrepreneurship among youth.","benefit":"₹10 lakh grant for innovators","eligibility":{"occupation":["student","unemployed"],"max_age":35},"apply_link":"https://aim.gov.in","icon":"🔬"},
]
def match_schemes(age: int, gender: str, income: int, occupation: str, category: str):
    matched = []
    for scheme in schemes:
        e = scheme["eligibility"]
        if "min_age"    in e and age < e["min_age"]:          continue
        if "max_age"    in e and age > e["max_age"]:          continue
        if "max_income" in e and income > e["max_income"]:    continue
        if "gender"     in e and gender.lower() not in e["gender"]:    continue
        if "occupation" in e and occupation.lower() not in e["occupation"]: continue
        if "category"   in e and category.upper() not in e["category"]:    continue
        matched.append(scheme)
    return matched
